(function (global) {
  'use strict';
  var TRENDING_SEARCHES = [
  'React Developer',
  'Remote Jobs',
  'Backend Engineer',
  'Product Manager',
  'UI/UX Designer',
];
  var FEATURED_COMPANIES = [
  { name: 'Systems Limited', logo: '💻', jobs: 24, location: 'Lahore' },
  { name: 'Careem', logo: '🚖', jobs: 18, location: 'Karachi' },
  { name: 'Jazz', logo: '📱', jobs: 12, location: 'Islamabad' },
  { name: 'S&P Global', logo: '📊', jobs: 9, location: 'Lahore' },
];
  var MOCK_JOBS = [
  {
    _id: 'job-001',
    title: 'Senior React Developer',
    company: 'Systems Limited',
    location: 'Lahore',
    salary: { min: 150000, max: 220000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Build and maintain modern React applications for enterprise clients. Collaborate with designers and backend engineers to deliver polished user experiences.',
    skills: ['React', 'TypeScript', 'Redux', 'CSS'],
    postedBy: 'employer-001',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '💼',
    remote: false,
    experience: '5+ years',
    category: 'Technology',
  },
  {
    _id: 'job-002',
    title: 'Backend Engineer (Node.js)',
    company: 'Careem',
    location: 'Karachi',
    salary: { min: 120000, max: 180000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Design scalable APIs and microservices using Node.js. Work closely with product managers to ship high-impact features.',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST'],
    postedBy: 'employer-002',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🚀',
    remote: true,
    experience: '3+ years',
    category: 'Engineering',
  },
  {
    _id: 'job-003',
    title: 'UI/UX Designer',
    company: 'Jazz',
    location: 'Islamabad',
    salary: { min: 100000, max: 150000, currency: 'PKR' },
    type: 'Contract',
    description: 'Create intuitive mobile and web experiences for financial products. Translate research into wireframes and high-fidelity mockups.',
    skills: ['Figma', 'Sketch', 'UX Research', 'Prototyping'],
    postedBy: 'employer-003',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🎨',
    remote: false,
    experience: '4+ years',
    category: 'Design',
  },
  {
    _id: 'job-004',
    title: 'Product Manager',
    company: 'S&P Global',
    location: 'Lahore',
    salary: { min: 180000, max: 260000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Lead product strategy and execution for data intelligence products. Partner with engineering, UX, and analytics teams.',
    skills: ['Product Management', 'Roadmaps', 'Agile', 'Stakeholder Management'],
    postedBy: 'employer-004',
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '📈',
    remote: true,
    experience: '6+ years',
    category: 'Product',
  },
  {
    _id: 'job-005',
    title: 'Junior DevOps Engineer',
    company: 'Careem',
    location: 'Karachi',
    salary: { min: 90000, max: 130000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Support deployment pipelines and infrastructure automation using Docker, Kubernetes, and CI/CD tools.',
    skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD'],
    postedBy: 'employer-002',
    deadline: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🛠️',
    remote: false,
    experience: '2+ years',
    category: 'Infrastructure',
  },
  {
    _id: 'job-006',
    title: 'Finance Analyst',
    company: 'Jazz',
    location: 'Islamabad',
    salary: { min: 110000, max: 140000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Analyze financial performance and forecasting for enterprise products. Build dashboards and reports for senior management.',
    skills: ['Excel', 'Power BI', 'Financial Modeling', 'Data Analysis'],
    postedBy: 'employer-003',
    deadline: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '💰',
    remote: true,
    experience: '3+ years',
    category: 'Finance',
  },
  {
    _id: 'job-007',
    title: 'Digital Marketing Specialist',
    company: 'Systems Limited',
    location: 'Lahore',
    salary: { min: 85000, max: 115000, currency: 'PKR' },
    type: 'Part-time',
    description: 'Plan and execute digital marketing campaigns, including social media, email, and search advertising.',
    skills: ['SEO', 'Google Ads', 'Content Marketing', 'Analytics'],
    postedBy: 'employer-001',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '📣',
    remote: true,
    experience: '2+ years',
    category: 'Marketing',
  },
  {
    _id: 'job-008',
    title: 'Full Stack Developer',
    company: 'S&P Global',
    location: 'Lahore',
    salary: { min: 140000, max: 200000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Work across frontend and backend systems, building customer-facing dashboards and APIs.',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    postedBy: 'employer-004',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🌐',
    remote: false,
    experience: '4+ years',
    category: 'Technology',
  },
  {
    _id: 'job-009',
    title: 'Customer Success Manager',
    company: 'Careem',
    location: 'Karachi',
    salary: { min: 95000, max: 120000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Manage customer relationships, onboard new clients, and help ensure successful product adoption.',
    skills: ['Customer Success', 'Communication', 'CRM', 'Project Management'],
    postedBy: 'employer-002',
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🤝',
    remote: true,
    experience: '3+ years',
    category: 'Customer Support',
  },
  {
    _id: 'job-010',
    title: 'QA Engineer',
    company: 'Jazz',
    location: 'Islamabad',
    salary: { min: 85000, max: 110000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Test web and mobile applications, automate regression suites, and work closely with QA and engineering teams.',
    skills: ['Test Automation', 'Selenium', 'Jest', 'API Testing'],
    postedBy: 'employer-003',
    deadline: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🧪',
    remote: false,
    experience: '2+ years',
    category: 'Quality Assurance',
  },
  {
    _id: 'job-011',
    title: 'Graphic Designer',
    company: 'Systems Limited',
    location: 'Lahore',
    salary: { min: 70000, max: 95000, currency: 'PKR' },
    type: 'Contract',
    description: 'Create visual assets, marketing collateral, and illustrations for digital campaigns.',
    skills: ['Adobe Creative Suite', 'Illustration', 'Brand Design'],
    postedBy: 'employer-001',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🖌️',
    remote: true,
    experience: '3+ years',
    category: 'Design',
  },
  {
    _id: 'job-012',
    title: 'HR Specialist',
    company: 'Jazz',
    location: 'Islamabad',
    salary: { min: 90000, max: 125000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Manage recruitment, onboarding, and employee engagement initiatives for cross-functional teams.',
    skills: ['HR', 'Recruitment', 'Employee Relations', 'Payroll'],
    postedBy: 'employer-003',
    deadline: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '🧑‍💼',
    remote: false,
    experience: '4+ years',
    category: 'Human Resources',
  },
  {
    _id: 'job-013',
    title: 'Data Analyst',
    company: 'S&P Global',
    location: 'Lahore',
    salary: { min: 115000, max: 145000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Perform data analysis, build dashboards, and support business teams with actionable insights.',
    skills: ['SQL', 'Tableau', 'Python', 'Excel'],
    postedBy: 'employer-004',
    deadline: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '📊',
    remote: false,
    experience: '3+ years',
    category: 'Analytics',
  },
  {
    _id: 'job-014',
    title: 'Social Media Manager',
    company: 'Careem',
    location: 'Karachi',
    salary: { min: 80000, max: 105000, currency: 'PKR' },
    type: 'Part-time',
    description: 'Manage social channels, run audience campaigns, and grow brand awareness across digital platforms.',
    skills: ['Social Media', 'Copywriting', 'Analytics', 'Community Management'],
    postedBy: 'employer-002',
    deadline: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '📱',
    remote: true,
    experience: '2+ years',
    category: 'Marketing',
  },
  {
    _id: 'job-015',
    title: 'Sales Operations Coordinator',
    company: 'Systems Limited',
    location: 'Lahore',
    salary: { min: 85000, max: 115000, currency: 'PKR' },
    type: 'Full-time',
    description: 'Support sales operations with reporting, process optimization, and CRM management.',
    skills: ['Sales Operations', 'CRM', 'Reporting', 'Excel'],
    postedBy: 'employer-001',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    logo: '📦',
    remote: false,
    experience: '2+ years',
    category: 'Operations',
  },
];
  function getAllJobs() {
    var employer = JSON.parse(localStorage.getItem('indeed_employer_jobs') || '[]');
    return MOCK_JOBS.concat(employer);
  }
  function getJobById(id) {
    return getAllJobs().find(function (j) { return j._id === id; }) || null;
  }
  global.IndeedData = {
    TRENDING_SEARCHES: TRENDING_SEARCHES,
    FEATURED_COMPANIES: FEATURED_COMPANIES,
    MOCK_JOBS: MOCK_JOBS,
    getAllJobs: getAllJobs,
    getJobById: getJobById,
  };
})(window);
